version: '3'
services:
  docker-lg1:
    container_name: docker-lg1
    hostname: docker-lg1
    image: neotys/neoload-loadgenerator:7.1
    environment:
      - LOADGENERATOR_XMX=-Xmx512m
    networks:
      - neoload
  docker-lg2:
    container_name: docker-lg2
    hostname: docker-lg2
    image: neotys/neoload-loadgenerator:7.1
    environment:
      - LOADGENERATOR_XMX=-Xmx512m
    networks:
      - neoload

networks:
  neoload:
    external:
      name: neoload
